---
name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - uses: pre-commit/action@v3.0.0
    # pre-commit/action is deprecated.
    # See https://github.com/marketplace/actions/pre-commit.
    #
    # But we have to use it because pre-commit.ci doesn't
    # seem to support Docker hooks currently on 2023/03/23.
